### ISSUE TITLE
request new entry

### ISSUE THREAD

**Issue by ka2ddo** [hessu/aprs-deviceid#13]
Greetings. Please add my software to your device index.

APJYC?
vendor: Andrew Pavlin, KA2DDO
class: software
model: YAAC (Yet Another APRS Client)

**Comment by hessu** [comment]
Hi,

In tocalls.txt you've been assigned APJYnn, i.e. with two characters for the version number. Probably that should be used instead of APJYC so that you'd have more space for the version?

**Comment by hessu** [comment]
tocalls.yaml already has "tocall: APJY??" so that'll catch APJYC? too, I'll close this ticket as it seems to be handled correctly.
