### ISSUE TITLE
Kantronics KAM-XL

### ISSUE THREAD

**Issue by PhirePhly** [hessu/aprs-deviceid#15]
Per [this thread on the Yahoo APRS list](https://groups.yahoo.com/neo/groups/APRS/conversations/topics/14067;_ylc=X3oDMTMzbHJjZGhpBF9TAzk3MzU5NzE0BGdycElkAzE1NzYEZ3Jwc3BJZAMxNzA1MDYzMTA4BG1zZ0lkAzE0MDc0BHNlYwNmdHIEc2xrA3Z0cGMEc3RpbWUDMTUwNDU1MjE0MAR0cGNJZAMxNDA2Nw--), Bob thinks `APNKXL` is obviously the TNC-ID for the KAM-XL. 

I'll work on getting him to update the tocalls.txt file. Closing this issue will follow.

**Comment by hessu** [comment]
APNKXL is currently not in Bob's list (just a status update).

**Comment by hessu** [comment]
APNKXL still not in Bob's list, closing as inactive.
