### ISSUE TITLE
Sorting of tocall entries in yaml file

### ISSUE THREAD

**Issue by PhirePhly** [hessu/aprs-deviceid#16]
What is the current policy for how entries are ordered in the base yaml file? I can't figure out how they're sorted.

Would you accept a PR to place all the entries in alphabetical order with comment headers for every `APn` prefix much like how the tocalls.txt file is set up? This would break any pending patches (of which I see none publicly) but would make working on the database a little easier in the long run.

**Comment by hessu** [comment]
They're currently not ordered; technically the ordering in this file does not matter, other than for human editors.
Probably, but I don't know if comments for the sections are needed, the classes of prefixes in tocalls.txt are frequently violated in there.
