### ISSUE TITLE
easyAPRS

### ISSUE THREAD

**Issue by ayasystems** [hessu/aprs-deviceid#18]
Could you assing me a new device id?

vendor: EA4GKQ ( ea4gkq@ayasystems.com )
model: Tracker
OS: No OS
Features: Two diferent devices:
An ESP8266 + GPS . It sends our position over tcp/ip
An Arduino nano + GPS + DRA818. It will sends beacons over RF

I'm going to public the code when all will be ready and the PCB design. All free of course.

Regards

**Comment by ayasystems** [comment]
You can find easyAPRS details here ->  https://github.com/ayasystems/EASY-APRS

**Comment by hessu** [comment]
Hi,
Sorry for the slow reply. Please check the README here, under the title "Adding new devices", and get in touch with Bob Bruninga to have an ID assigned:
https://github.com/hessu/aprs-deviceid
