### ISSUE TITLE
Please add tocall APECAN

### ISSUE THREAD

**Issue by tkrahn** [hessu/aprs-deviceid#2]
APE??? was originally allocated for telemetry devices. Therefore I used APECAN as a special subset for my open source / open hardware balloon trackers since they are also kind of telemetry devices.

 "APECAN" : {
"model" : "Pecan Pico APRS Balloon Tracker",
"class" : "tracker",
"vendor" : "Open Source / Open Hardware by KT5TK/DL4MDW and DL7AD"
},

See
https://kt5tk.wordpress.com/
https://github.com/tkrahn/pecanpico5a

Thanks,

Thomas

**Comment by hessu** [comment]
Hi,

I'll bounce this to Bob Bruninga over email so that we can it added in tocalls.txt first. That's still the master index for now.

**Comment by hessu** [comment]
Bob added it (http://aprs.org/aprs11/tocalls.txt).

The vendor strings would be good to be shorter, compare to the other examples at https://github.com/hessu/aprs-deviceid/blob/master/tocalls.yaml - this will typically be shown on a single line, sometimes on a small mobile device. I'll put KT5TK/DL7AD for the time being?

**Comment by tkrahn** [comment]
Dear Heikki,

Thank you very much! Great to have it official and not to conflict with 
anyone else.

Thomas

**Comment by hessu** [comment]
You're welcome!
