### ISSUE TITLE
Request new entry for APRARX (radiosonde_auto_rx)

### ISSUE THREAD

**Issue by darksidelemm** [hessu/aprs-deviceid#20]
Hi,

Bob has just approved my tocall entry of APRARX, for my open source radiosonde_auto_rx software, which is available here: https://github.com/projecthorus/radiosonde_auto_rx

Vendor: Open Source
Model: radiosonde_auto_rx
class: software
os: Linux/Unix

If this could be added, that would be much appreciated!

Thanks,
Mark VK5QI

**Comment by hessu** [comment]
Hi,

If you're into programming, could you consider creating a Pull Request for tocalls.yaml yourself? Don't run the generator, I'll do that after the merge. I'm a bit busy with other stuff in the aprs.fi system, so any help is appreciated.

**Comment by darksidelemm** [comment]
About to head off to a conference, but will do when I get a spare minute...

**Comment by hessu** [comment]
Thank you very much! I'll deploy this in the next update round of aprs.fi, pretty soon.
