### ISSUE TITLE
Please add tocall APAVT5

### ISSUE THREAD

**Issue by dconzatti** [hessu/aprs-deviceid#3]
I emailed Bob and he has added this to tocalls.txt. Just submitting this ticket to have this file updated. 
06 Apr 15 added APAVT5 for SainSonic AP510 - a 1watt tracker 

Thanks
Dave VA7ZAT

**Comment by hessu** [comment]
Done, in commit 3ccce52735743393d8c04a0951940b4935838c31. Just to confirm, are you the/an author of the software for that product?

**Comment by dconzatti** [comment]
Thanks!

I'm not an Author for the product, Just a user of the tracker. More details on the development of it can be found here:
http://www.y027.com/dvbbs8/dispbbs.asp?boardid=5&id=829

Thank you again for adding it, I'm looking forward to seeing it added on aprs.fi.

Dave VA7ZAT
