### ISSUE TITLE
No love for APATxx?

### ISSUE THREAD

**Issue by W0CHP** [hessu/aprs-deviceid#39]
I see that APATxx has entries in the YAML file, however, is this allocation/device and vendor not live/in production on aprs.fi Because I am not seeing it in the "Device: " field.

Thanks.

**Comment by hessu** [comment]
Not an issue of aprs-deviceid, so closing as invalid here.

**Comment by W0CHP** [comment]
Sorry about that! Is there a more appropriate place that I should be submitting these?

**Comment by hessu** [comment]
The aprs.fi group is at https://groups.google.com/g/aprsfi but this issue might have been fixed already; the automatic update of tocalls.yaml was stuck.

**Comment by W0CHP** [comment]
Thank you sir! Again, sorry about that! 73.
