### ISSUE TITLE
More precision for Mice

### ISSUE THREAD

**Issue by akhenakh** [hessu/aprs-deviceid#4]
Hi,

From the specs it says, example for the FT1D, ends with _$ and starts with `
the TinyTrack4 starts with a different prefix ' but the exported jsons don't mention the prefix, is it a mistake ?
```
`......_$  Yaesu FT1D      [New in Dec 2012]
'......|3  Byonics TinyTrack3 (TT3)  
'......|4  Byonics TinyTrack4 (TT4)
```
```
      "|3" : {
         "model" : "TinyTrak3",
         "class" : "tracker",
         "vendor" : "Byonics"
      },
```
Thanks

**Comment by hessu** [comment]
Theprefix character (` vs ') indicates messaging capability.

http://www.aprs.org/aprs12/mic-e-types.txt

**Comment by akhenakh** [comment]
Makes sense, thank you.
