### ISSUE TITLE
New APRS Device ID

### ISSUE THREAD

**Issue by barisdinc** [hessu/aprs-deviceid#41]
HI,

Bob added our new device to database (tocalls.txt), we will be veru happy if you can add it do device ist as well.
Here is the information ;

tocall: APIZCI
vendor: IZCI APRS Tracker by TA7W/OH2UDS and TA6AEU
model: hymTR IZCI
class: embedded
os: none

**Comment by hessu** [comment]
Hi, how about this:

 - tocall: APIZCI
   vendor: TA7W/OH2UDS and TA6AEU
   model: hymTR IZCI Tracker
   class: tracker
   os: embedded

The classes are listed in the beginning of the tocalls.yml document, this is apparently a tracker. The os: field is set to embedded for OS-less devices. I also cleared out the distinction between vendor (maker) and model; are you happy with this model string?

**Comment by barisdinc** [comment]
yes, thank you.... I just confused while filling those, but now it is clear
Thanks

Baris
OH2UDS/TA7W

**Comment by hessu** [comment]
Thanks, done!

**Comment by barisdinc** [comment]
hi,
It's been a month that the tocall files updated but still can't see the DEVICE in aprs.fi ... Do I have to do something else to get APIZCI being decoded right ?

![image](https://user-images.githubusercontent.com/7115603/100730890-54dfc800-33d3-11eb-9307-0fa74a8b1d72.png)

**Comment by barisdinc** [comment]
Hi,

Sorry for bothering you again, but for IZCI Tracker the type is reported as
D-STAR on aprs.fi, what else should I do to get it reported as izci
tracker...

Thanks
Baris
OH2UDS / TA7W


[image: izci.png]
please check the area in *RED BOX*
