### ISSUE TITLE
New device ID

### ISSUE THREAD

**Issue by kf7eel** [hessu/aprs-deviceid#42]
I have a new device ID to add to the list. Bob just added it to his.
This is for HBLink, a digital radio linking server. I created an APRS gateway for HBLink to take GPS coordinates sent by some DMR radios and format and upload an APRS location packet. It does not support APRS messaging at this time, however, I am working on that feature now. See it here [https://github.com/kf7eel/hblink3](https://github.com/kf7eel/hblink3).

 - tocall: APHBL?
   vendor: KF7EEL
   model: HBLink D-APRS Gateway
   class: software

**Comment by hessu** [comment]
Thanks for the note, added!
