### ISSUE TITLE
APNIC4 New aprs-device

### ISSUE THREAD

**Issue by SQ5EKU** [hessu/aprs-deviceid#49]
hi,
could you please create a new 'tocall' for (ESP/STM32 mix)  devices.
more information - http://sq5eku.blogspot.com/p/bida-traker.html

tocall: APNIC4
vendor: SQ5EKU
model: BidaTrak
class: embedded

thanks in advance
Robert, SQ5EKU

**Comment by hessu** [comment]
Hi!

Added in 3894979351d0adcc6bf2a396e00ba33ef9e1e90a with class: tracker, os: embedded.

Thanks!
