### ISSUE TITLE
Clarify APCSS is CubeSatSim 

### ISSUE THREAD

**Issue by alanbjohnston** [hessu/aprs-deviceid#58]
Hi,

Thanks for adding total APCSS to your list!  Right now it says:

 - tocall: APCSS
   vendor: AMSAT
   model: CubeSat

It would be good to change the model field to say:

   model: CubeSatSim CubeSat Simulator

Since it isn't an on orbit CubeSat but an educational simulator.

Thanks and 73!
Alan

**Comment by hessu** [comment]
Hi!

Thanks for the clarification, I've just committed a fix with this model string.
